# Build matrix / environment variable are explained on:
# https://docs.travis-ci.com/user/customizing-the-build/
# This file can be validated on:
# http://lint.travis-ci.org/

language: c

    - os: linux
      compiler: gcc

  - Gtest/googletest-master/ci/install-${TRAVIS_OS_NAME}.sh
  - Gtest/googletest-master/ci/env-${TRAVIS_OS_NAME}.sh
  - Gtest/googletest-master/ci/log-config.sh

script: Gtest/googletest-master/ci/travis.sh


