dist: trusty
sudo: required

language: c

branches:
  only:
    - c++

os: linux

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-6
      - valgrind
      - cppcheck

script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - export CC=/usr/bin/gcc-6
  - cd ./task1
  - mkdir build
  - cd build
  - cmake ..
  - make
  - valgrind --tool=memcheck --leak-check=full ./task
  - cppcheck --enable=all --std=c99 --check-config --suppress=missingIncludeSystem -I ../project/include/ ../project/src/
  - ./task