# Build matrix / environment variable are explained on:
# https://docs.travis-ci.com/user/customizing-the-build/
# This file can be validated on:
# http://lint.travis-ci.org/

language: c

# Define the matrix explicitly, manually expanding the combinations of (os, compiler, env).
# It is more tedious, but grants us far more flexibility.
os:
  # будем прогонять CI и на Linux, и на Mac OS X...
  - linux

compiler:
  # ... и с помощью GCC, и Clang
  - gcc
  - clang

env:
  # список переменных окружения, влияющих на матрицу сборки:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-6
      - valgrind
      - cppcheck

script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - export CC=/usr/bin/gcc-6
  - cd ./task1
  - mkdir build
  - cd build
  - cmake ..
  - make
  - valgrind --tool=memcheck --leak-check=full ./task ../project/tests/test.txt
  - cppcheck --enable=all --std=c99 --check-config --suppress=missingIncludeSystem -I ../project/include/ ../project/src/
  - ./task ../project/tests/test.txt
